# Generated by Django 4.2 on 2023-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
